(Π_STATE
  (time "2026-03-20T15:28:10Z")
  (branch "main")
  (pre_head "6ec01e6")
  (dirty true)
  (checks
    (check (status passed) (command "clojure -M -e (require promptbench.eval.runner promptbench.eval.report promptbench.eval.stats)"))
    (check (status passed) (command "clojure -M:test -n promptbench.judges-test -n promptbench.eval-stats-test"))
    (check (status passed) (command "clj -M -m promptbench.eval.runner direct-user smoke across working proxy models") (note "from 2026-03-20T07:06:03Z receipt"))
  )
  (repo_notes
    (upstream "origin/main")
    (status_digest "befb-671c-15c4-9cbd")
    (note "Large data/judge-cache and data/runs artifacts are intentionally preserved in-repo for repeatable benchmark forensics.")
    (changed_file "AGENTS.md")
    (changed_file "receipts.log")
    (changed_file "specs/drafts/shibboleth-danger-gate.md")
    (changed_file "src/promptbench/eval/judges.clj")
    (changed_file "src/promptbench/eval/report.clj")
    (changed_file "src/promptbench/eval/runner.clj")
    (changed_file "test/promptbench/judges_test.clj")
    (changed_file "data/judge-cache/cache.edn")
    (changed_file "data/judge-cache/claude46-small-rerun-kimi-cache.edn")
    (changed_file "data/judge-cache/significance-direct-user-300-seed20260319-kimi-cache.edn")
    (changed_file "data/judge-cache/significance-direct-user-600-kimi-cache.edn")
    (changed_file "docs/evaluation/direct-user-significance-summary-2026-03-19.md")
    (changed_file "scripts/overnight_model_sweep.sh")
    (changed_file "specs/drafts/eval-significance-sweeps.md")
    (changed_file "specs/drafts/remote-deploy-and-overnight-model-sweep.md")
    (changed_file "src/promptbench/eval/stats.clj")
    (changed_file "test/promptbench/eval_stats_test.clj")
  )
)
